# This is a basic workflow to help you get started with Actions

name: Bootcamp 2020 Project 02

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Setup Node.js Environment
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12 
    
    - name: GitHub Action for Yarn or npm
      uses: Borales/actions-yarn@v2.1.0
      with:
        #Yarn Command
        cmd: install #yarn install or npm install
    
    - name: Creating Build
      run: yarn build #yarn build or npm run-script build
      
    - name: Installing Surge
      run: npm install -g surge
      
    - name: Deploying on Surge
      run: surge ./build http://bc2020_aproj02.surge.sh/ --token ${{secrets.SURGE_TOKEN}}
